# ubi 9.4-1227.1726694542
FROM registry.access.redhat.com/ubi9-minimal@sha256:f5d2c6a1e0c86e4234ea601552dbabb4ced0e013a1efcbfb439f1f6a7a9275b0

LABEL org.opencontainers.image.authors="CodeReady Containers <devtools-cdk@redhat.com>"

ENV AWS_CLI_VERSION 2.17.63
ENV AWS_CLI_URL https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip

# YQ
ENV YQ_VERSION=4.11.2
ENV YQ_BINARY_URL=https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64

RUN microdnf install -y openssh-clients sshpass unzip zip bash jq findutils \
    && curl -Lo /usr/local/bin/yq "${YQ_BINARY_URL}" \
    && chmod +x /usr/local/bin/yq \
    && curl ${AWS_CLI_URL} -o awscliv2.zip \
    && unzip awscliv2.zip \
    && ./aws/install \
    && microdnf clean all \
  	&& rm -rf /var/cache/yum

